#include <windows.h>
#include <d3dcompiler.h>
#include <wrl/client.h>
#include <cstring>
#include <filesystem>
#include <fstream>
#include <iomanip>
#include <iostream>
#include <sstream>
#include <stdexcept>
#include <string>
#include "../gpufft_shaders.h"

using Microsoft::WRL::ComPtr;

int wmain(int argc, wchar_t** argv)
{
    try
    {
        if (argc != 2) throw std::runtime_error("Expected generated header path");
        std::filesystem::path output(argv[1]);
        auto temporary = output;
        temporary += L".tmp";
        std::ofstream file(temporary, std::ios::binary | std::ios::trunc);
        if (!file) throw std::runtime_error("Cannot create shader header");
        file << "// Generated by compile_shaders.cpp; do not edit.\n#pragma once\n";
        file << "struct PrecompiledCs { const void* data; size_t size; };\n";
        std::ostringstream lookup;
        lookup << "static inline PrecompiledCs FindPrecompiledCs(const char* source, const D3D_SHADER_MACRO* defines)\n{\n"
            "    int stages = 4, threads = 64, packed = 0;\n"
            "    if (defines) for (auto* d = defines; d->Name; ++d)\n"
            "    {\n"
            "        if (!d->Definition) return {};\n"
            "        char* end;\n"
            "        long value = strtol(d->Definition, &end, 10);\n"
            "        if (end == d->Definition || *end || value < 0 || value > 256) return {};\n"
            "        if (strcmp(d->Name, \"FFT_STAGES\") == 0) stages = static_cast<int>(value);\n"
            "        else if (strcmp(d->Name, \"FFT_THREADS\") == 0) threads = static_cast<int>(value);\n"
            "        else if (strcmp(d->Name, \"FFT_PACKED_INPUT\") == 0) packed = static_cast<int>(value);\n"
            "        else return {};\n"
            "    }\n";
        int count = 0;
        auto compile = [&](const char* name, const char* source, const D3D_SHADER_MACRO* defines, const std::string& condition)
        {
            ComPtr<ID3DBlob> code, error;
            HRESULT hr = D3DCompile(source, strlen(source), nullptr, defines, nullptr, "main", "cs_5_0",
                D3DCOMPILE_OPTIMIZATION_LEVEL3, 0, &code, &error);
            if (FAILED(hr))
            {
                if (error) std::cerr.write(static_cast<const char*>(error->GetBufferPointer()), error->GetBufferSize());
                throw std::runtime_error(std::string("Shader compilation failed: ") + name);
            }
            const auto* bytes = static_cast<const unsigned char*>(code->GetBufferPointer());
            std::string symbol = "csBytecode" + std::to_string(count++);
            file << "inline constexpr unsigned char " << symbol << "[] = {" << std::hex;
            for (size_t i = 0; i < code->GetBufferSize(); ++i)
            {
                if (i % 24 == 0) file << '\n';
                file << "0x" << std::setw(2) << std::setfill('0') << static_cast<int>(bytes[i]) << ',';
            }
            file << "\n};\n" << std::dec;
            lookup << "    if (source == " << name << " && " << condition << ") return { " << symbol << ", sizeof(" << symbol << ") };\n";
        };
        struct Shader { const char* name; const char* source; };
        const Shader shaders[] = {
            { "kShaderPackedToComplex", kShaderPackedToComplex }, { "kShaderStockham", kShaderStockham },
            { "kShaderStockhamPair", kShaderStockhamPair }, { "kShaderDbConvert", kShaderDbConvert },
            { "kShaderSpectrumReduce", kShaderSpectrumReduce }, { "kShaderChannelMix", kShaderChannelMix },
            { "kShaderChannelFilter", kShaderChannelFilter }, { "kShaderChannelBatchMix", kShaderChannelBatchMix },
            { "kShaderChannelBatchFilter", kShaderChannelBatchFilter }
        };
        for (const auto& shader : shaders) compile(shader.name, shader.source, nullptr, "!defines");
        for (int stages = 1; stages <= 6; ++stages)
        for (int threads : { 32, 64, 128, 256 })
        for (int packed : { 0, 1 })
        {
            std::string s = std::to_string(stages), t = std::to_string(threads), p = std::to_string(packed);
            const D3D_SHADER_MACRO defines[] = { { "FFT_STAGES", s.c_str() }, { "FFT_THREADS", t.c_str() },
                { "FFT_PACKED_INPUT", p.c_str() }, { nullptr, nullptr } };
            compile("kShaderStockhamFused", kShaderStockhamFused, defines,
                "stages == " + s + " && threads == " + t + " && packed == " + p);
        }
        file << lookup.str() << "    return {};\n}\n";
        file.close();
        if (!file || !MoveFileExW(temporary.c_str(), output.c_str(), MOVEFILE_REPLACE_EXISTING))
            throw std::runtime_error("Cannot publish shader header");
        std::cout << "Precompiled " << count << " compute shaders\n";
        return 0;
    }
    catch (const std::exception& error) { std::cerr << error.what() << '\n'; return 1; }
}
